-- 1. Create 'trips' Table (Master Table)
create table if not exists public.trips (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid default auth.uid(), -- Link to Supabase Auth User
    name text not null,
    start_date date,
    end_date date,
    cover_image text,
    location text
);

-- Enable RLS for trips
alter table public.trips enable row level security;

-- Policy: Users can only see their own trips
create policy "Users can view own trips"
    on public.trips for select
    using (auth.uid() = user_id);

create policy "Users can insert own trips"
    on public.trips for insert
    with check (auth.uid() = user_id);

create policy "Users can update own trips"
    on public.trips for update
    using (auth.uid() = user_id);

-- 2. Modify Existing Tables to link to 'trips'

-- A. trip_config
-- Note: In a pure multi-trip schema, trip_config could be merged into 'trips', 
-- but for now we will just link it to keep compatibility.
alter table public.trip_config 
add column if not exists trip_id bigint references public.trips(id) on delete cascade;

-- B. itineraries
alter table public.itineraries 
add column if not exists trip_id bigint references public.trips(id) on delete cascade;

-- C. expenses
alter table public.expenses 
add column if not exists trip_id bigint references public.trips(id) on delete cascade;


-- 3. Update RLS Policies for Child Tables to check trip ownership
-- (This is a simplified approach; ideally you check if the user owns the linked trip)

-- Example for expenses:
create policy "Users can view expenses of their trips"
    on public.expenses for select
    using (
        exists (
            select 1 from public.trips
            where trips.id = expenses.trip_id
            and trips.user_id = auth.uid()
        )
    );

-- 4. Seed Dummy Trip (Optional - For Dev)
-- This tries to associate existing orphan records to a new dummy trip for safety
do $$
declare
    new_trip_id bigint;
begin
    -- Create a default trip if none exists
    insert into public.trips (name, location, start_date, end_date)
    values ('My First Trip', 'Default Location', '2025-01-01', '2025-01-05')
    returning id into new_trip_id;

    -- Link existing orphan records to this new trip
    update public.itineraries set trip_id = new_trip_id where trip_id is null;
    update public.expenses set trip_id = new_trip_id where trip_id is null;
    update public.trip_config set trip_id = new_trip_id where trip_id is null;
end $$;
