-- Enable necessary extensions
-- Note: Supabase projects usually have UUID enabled by default, but it's good practice.
create extension if not exists "uuid-ossp";

-- -----------------------------------------------------------------------------
-- 1. trip_config (單行設定檔)
-- -----------------------------------------------------------------------------
create table if not exists public.trip_config (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    companions jsonb default '[]'::jsonb,
    flight_info jsonb default '{}'::jsonb,
    hotel_info jsonb default '{}'::jsonb
);

-- Enable RLS
alter table public.trip_config enable row level security;

-- Policy: Public Read (Anyone can view the trip config - typical for shared trip apps)
create policy "Public Read Access"
    on public.trip_config for select
    using (true);

-- Policy: Auth Write (Only authenticated users can update)
create policy "Authenticated Update Access"
    on public.trip_config for update
    using (auth.role() = 'authenticated');
    
-- Policy: Auth Insert (Only authenticated users can insert, though typically there's only one row)
create policy "Authenticated Insert Access"
    on public.trip_config for insert
    with check (auth.role() = 'authenticated');


-- -----------------------------------------------------------------------------
-- 2. itineraries (行程表)
-- -----------------------------------------------------------------------------
create table if not exists public.itineraries (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    date date not null,
    start_time time without time zone,
    location text not null,
    category text check (category in ('transport', 'activity', 'food', 'stay')),
    notes text
);

-- Enable RLS
alter table public.itineraries enable row level security;

-- Policy: Public Read
create policy "Public Read Access itineraries"
    on public.itineraries for select
    using (true);

-- Policy: Auth Write (Insert/Update/Delete) for Authenticated Users
create policy "Authenticated Write Access itineraries"
    on public.itineraries for all
    using (auth.role() = 'authenticated');


-- -----------------------------------------------------------------------------
-- 3. expenses (記帳表)
-- -----------------------------------------------------------------------------
create table if not exists public.expenses (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    item_name text not null,
    amount numeric not null,
    currency text not null default 'TWD',
    payer text not null,
    split_details jsonb default '{}'::jsonb
);

-- Enable RLS
alter table public.expenses enable row level security;

-- Policy: Public Read
create policy "Public Read Access expenses"
    on public.expenses for select
    using (true);

-- Policy: Auth Write (Insert/Update/Delete) for Authenticated Users
create policy "Authenticated Write Access expenses"
    on public.expenses for all
    using (auth.role() = 'authenticated');


-- -----------------------------------------------------------------------------
-- Seed Data (Optional - to initialize the trip config)
-- -----------------------------------------------------------------------------
insert into public.trip_config (companions, flight_info, hotel_info)
values (
    '["Alice", "Bob"]'::jsonb, 
    '{"outbound": "BR198", "inbound": "BR197"}'::jsonb, 
    '{"name": "Tokyo Hotel", "address": "Shinjuku"}'::jsonb
)
on conflict do nothing;
